language: node_js
node_js:
  - "node"

before_install:
  - rvm install 2.5.0

install:
  - make install

script:
  - make build

branches:
  only:
    - master

notifications:
  email:
    on_failure: always
    on_success: never
