language: node_js
node_js:
  - "node"

install:
  - npm i -g markdownlint-cli

script:
  - markdownlint docs --config docs/.markdownlint.json

notifications:
  - email:
    - on_failure: always
    - on_success: never
